### ISSUE TITLE
Setup Packrat

### ISSUE THREAD

**Issue by jeremiedb** [dot-layer/modelisation-predictive-R#16]
Est-ce que vous avez eu des issues avec packarat?

Je suis sur R 3.5.1 et j'ai eu à me battre un peu avec packrat. J'ai réglé le problème en suivant https://github.com/rstudio/packrat/issues/524: 

```
rm -rf packrat/src packrat/lib*

install.packages("devtools")
devtools::install_github("rstudio/packrat")
library(packrat)
packrat::set_opts(symlink.system.packages = TRUE)
packrat::restore()
````

C'est la première fois que je travaille avec packarat, s'il faut faire une opération comme `packrat::restore()` avant la première utilisation du repo, alors ce serait bien de l'indiquer dans le getting started du README.

**Comment by stecaron** [comment]
J'ai utilisé packrat, mais après avoir parlé avec @jplecavalier on s'est dit que peut-être ça serait vraiment plus simple de ne pas l'utiliser pour faire le livre. C'est peut-être un overkill. Mais ouais faut habituellement faire un `packrat::restore()` .. j'avoue que ça devrait faire partie du README. Si on le garde, on le rajoutera dans le README. 

Pensez-vous qu'on devrait cancel le packrat @jeremiedb @jplecavalier @samperochkin @caronl ?

**Comment by samperochkin** [comment]
Je vous fais totalement confiance là-dessus.

**Comment by stecaron** [comment]
Qu'est que vous diriez qu'on le remove pour développer le livre (question d'être plus efficace en développement) et le packrat à la fin pour augmenter les odds qu'il demeure reproductible dans le futur?

**Comment by stecaron** [comment]
Question : Comment on veut faire l'utilisation de packages dans le projet? On fait;
1. library(nomdupackage) au début du script?
2. on fait nomdupackage::nomdelafonction() a chaque fois qu'on appelle une fonction?
