### ISSUE TITLE
Ajout d'appendices

### ISSUE THREAD

**Issue by chblw** [dot-layer/modelisation-predictive-R#23]
Moi et @davebulaval préparons un workshop sur les tests automatisés dans un contexte de science des données en R. On pourrait préparer un appendice à votre livre qui résume les points plus essentiels à tester ?

**Comment by stecaron** [comment]
Ouais bonne idée @chblw ! C'était le genre de trucs qui étaient un peu "out of our scope", mais en faisant un appendice de même ça serait parfait !
