### ISSUE TITLE
Crash dans le preprocessing de main-eval.R

### ISSUE THREAD

**Issue by jeremiedb** [dot-layer/modelisation-predictive-R#25]
@stecaron @samperochkin 
J'ai un issue en tentant de rouler le script main-eval.R

J'ai roulé sans problème main-train.R, mais ensuite lors du preprocessing dans main-eval.R, j'ai le message d'rreur suivant: 

```
> data_test <- preprocessing(data_test, path_objects = "data/models/", train = FALSE)
 Show Traceback
 
 Rerun with Debug
 Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid bytes in UTF8 string.
          _journee", "start_quartier.côtedesneigesnotredamedegrâce", "
                     (right here) ------^ 
```

L'erreur proviendrait de la ligne 90 dans le scripts `preprocessing.R`: 
```
vars <- jsonlite::fromJSON(paste0(path_objects, "variables_a_conserver.json"))
```

Peut-être un cleaning des charactères spéciaux à effectuer?

**Comment by stecaron** [comment]
Uhmm je craignais que ca revienne nous hanter ces caractères spéciaux la ... Je m'occupe d'ajouter ca dans le pre-processing au PC.

**Comment by samperochkin** [comment]
Ouais, je crois que va falloir raccourcir les noms de toute façon... Dans mes summary c'est un peu difficile à déchiffrer avec les @£¢ un peu partout.

**Comment by samperochkin** [comment]
Je viens de checker pour un quick-fix, mais y'a des opérations plus tard qui plantent. Je vais te laisser faire ça, ça risque d'être plus clean...

**Comment by stecaron** [comment]
Je vais regarder ça ce soir dans le train !

**Comment by jeremiedb** [comment]
Comme discuté avec Sam, un quick fix possible serait un reguexp du genre: `> gsub("[^[:print:]]", "", x)`
Ou encore une approche pour forcer l'encoding avec stringi, discuté sur: https://stackoverflow.com/questions/23699271/force-character-vector-encoding-from-unknown-to-utf-8-in-r
