### ISSUE TITLE
Performance du preprocessing en mode inference

### ISSUE THREAD

**Issue by jeremiedb** [dot-layer/modelisation-predictive-R#27]
Le preprocessing pour un seul data point prend environs 2.2 sec., dont un 2 secondes passés à charger l'objet 1-hot: `readRDS(paste0(path_objects, "objet_un-chaud.rds"))`

Ce n'est pas impératif à ce moment-ci, mais je pense que ce serait bien d'avoir l'option de d'appeler la fonction de preprocessing avec les tables de dépendances déjà chargées. 
Pas certain de la meilleur manière, petu-être d'avoir un argument "..." à la fonction de manière à passer une liste variables d'objets, dont un-chaud ou encore les autres tables chargés à partir de json. Ou ajouter des arguments pour chacun de ces objects de façon explicite à la fonction de preprocessing.

**Comment by stecaron** [comment]
Ouais j'avais remarqué ça aussi, t'as raison ce qui prend le temps c'est le chargement de l'objet de one-hot encoding. Je m'étais dis que j'allais fouillé un peu plus pour comprendre la raison qui fait que l'objet est autant lourd (~87MB). 

Mais sinon j'aurais tendance à être assez d'accord avec ton idée de charger tous les objets (tables) de dépendances avant même de recevoir une observation à prédire .. ça pourrait être une option assez quick à implanter et ça fait du sens même quand tu y penses (un peu con de tout reloader à chaque inférence).
