### ISSUE TITLE
Rédaction de la section "Introduction"

### ISSUE THREAD

**Issue by stecaron** [dot-layer/modelisation-predictive-R#3]

**Comment by samperochkin** [comment]
SUGGESTION :
J'ai fait un squelette pour l'intro. @stecaron et moi pensons que ce serait pas pire si on décomposait le titre (Modélisation prédictive en R) en trois
- prédiction
- modélisation
- en R
Pour chaque terme on explique pourquoi il est dans le titre/ce qu'on veut dire par là.

Ensuite quelques commentaires sur les choix éditoriaux qu'on a fait (ligne directrice) et l'organisation du livre.

**Comment by samperochkin** [comment]
J'aimerais clarifier notre ligne directrice. Je suggère que, du début à la fin du livre, on suppose connu ce qui nous intéresse : Y (dans le sens, on a déjà une question)

Ensuite la section "collecte de données" touchera un peu à la question : quelles données pourraient être utiles? et des différents type de données/variables. Et ça décolle après...

Soyez pas gênés de changer tout ça. C'est juste un point de départ, qu'on active un peu.

**Comment by stecaron** [comment]
Pour répondre à ton commentaire @samperochkin, je suis d'accord qu'on "décompose le titre" dans la section introduction pour pas qu'on aille à repasser par dessus la base dans nos sections. Voici un peu plus de détails sur comment je vois cette décomposition la du titre:

1. Modélisation prédictive (expliquer c'est quoi high level le concept, i.e apprendre une fonction f(x) à partir de données)
2. Contexte de production (expliquer brièvement qu'on souhaite pas seulement bâtir le modèle, mais le bâtir d'une manière à pouvoir le réutiliser dans un environnement stable et reproductible)
3. En R (expliquer qu'on va appliquer cela en utilisant le language R et en proposant des packages, qui sont nos picks, mais qui ne sont pas les seuls)

Peut-être aussi parlé du fait que ces étapes sont d'une certaine manière "séquentielles", mais que ça veut pas dire pour autant que quand l'étape est fait, c'est terminé avec ça. On sait qu'il y a beaucoup de back-and-forth en modélisation donc serait une bonne idée mentionné le point dans l'intro. On peut en parler en mentionnant des concepts de "no free lunch" ou bien "no one-fits-all".

**Comment by jeremiedb** [comment]
Je suis un peu late to the show. Mais pour le point 1, est-ce que ça ne ferait pas du sens de présenter le tout sous l'angle des modèles supervisés? Je pense que la taxonomie supervisé/non-supervisé est assez commune et permettrait également de justifier la généralité d'application du tutorial. C'est-à-dire que ça s'applique aussi bien à un problème de classification que de régression, ou même de time-series. 

Pour le reste, j'aime bien ton split @stecaron
