### ISSUE TITLE
Rédaction de la section "Collecte de données"

### ISSUE THREAD

**Issue by stecaron** [dot-layer/modelisation-predictive-R#4]

**Comment by caronl** [comment]
Idées :
- GIGO (qualité)
- Prix
- Merge (clé, etc.)
- Quantité
- Format
- Storage
- Scraping (légalité/api/service)
- https://www.kaggle.com/datasets
- https://toolbox.google.com/datasetsearch
- https://www.reddit.com/r/datasets
- https://archive.ics.uci.edu/ml/index.php?fbclid=IwAR09F5grBOTCr1SS4v8gONEYeqk0DqqWpPdt1blmYF9ucZkhsQeM5T0E7ew
- http://donnees.ville.montreal.qc.ca/

Challenges : 
- rattacher la théorie à des packages R
