### ISSUE TITLE
Rédaction de la section "Pre-processing"

### ISSUE THREAD

**Issue by stecaron** [dot-layer/modelisation-predictive-R#6]

**Comment by stecaron** [comment]
Voici les points que j'aimerais traiter dans ma partie:

1. Nettoyage de données (imputations de données manquantes, gérer les outliers)
2. Réduction de données (sélection d'attributs, compression de données)
3. Transformation des données (normalisation, discretisation, one-hot encoding, création features)

Est-ce que ça fait du sens pour vous @jplecavalier et @samperochkin (étant donné que vous avez les sections avant et après moi)?

**Comment by samperochkin** [comment]
Pardon pour le délai. Ça fait ben du sens je crois. Surtout le "feature engeneering", dans l'optique où on veut qu'une question soit déjà sous-entendue (quoique non-spécifiée à part dans les exemples) du début à la fin.
