### ISSUE TITLE
Rédaction de la section "Déploiement de modele"

### ISSUE THREAD

**Issue by stecaron** [dot-layer/modelisation-predictive-R#8]

**Comment by meztez** [comment]
Selon vous, ça vaudrait la peine de présenter la combinaison .onLoad d'un package avec l'option preload au démarrage d'opencpu? Ou mettons juste une partie optimisation de la performance? btw, good job jeremiedb.

**Comment by jeremiedb** [comment]
Salut Bruno. Je ne sais pas si le .onLoad sera nécessaire dans notre situation, je crois que la mise en disponibilité des objets devrait se faire automatiquement via le sysdata.rda au moment du chargement de la librairie. Peut-être mettre LazyData à False?

Le preload dans opencpu m'apparaît comme un must à mentionner. Je l'avais particulièrement remarqué dans un test avec mxnet, une librairie assez lourde qui prend un 2-3 secondes à loader. Même pour xgboost, il y a un petit délai. Sans preload, ça risquerait de biaiser négativement la perception de performance de l'outil.
